### ISSUE TITLE
Develop a code of conduct for the repository

### ISSUE THREAD

**Issue by AbhiiVops** [AbhiiVops/OpenDevFellows#9]
### Create a code of conduct that outlines the expectations for behavior and interaction within the repository's community.

**Comment by 1sh22** [comment]
I would like to work on this. Please assign this to me

**Comment by AbhiiVops** [comment]
Hey @1sh22 
**Sure. I assign this issue to you.**

**Comment by AbhiiVops** [comment]
Hey @saharepiyush01 
Sure I assign this issue to you
Please follow the contributing guidelines
Thanks

**Comment by AbhiiVops** [comment]
Hey @saharepiyush01 this issue has been resolved by @1sh22 
You can go for some other issue
Looking forward to your contribution:)

**Comment by saharepiyush01** [comment]
ok then I will try some other thankyou
